# Generated by Django 5.2.7 on 2025-10-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_videojuegos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('anodepublicacion', models.IntegerField()),
                ('genero', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='videojuegos',
        ),
    ]
